[build]
  base = "anyspares-app"
  command = "npm run build:ssr"
  publish = "dist/anyspares-app/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# 🔁 Redirect all routes to index.html (Angular routing fix)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200