spring:
  application:
    name: ServiceGateway

  profiles:
    active: remote

server:
  port: 8181

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

cloud:
  gateway:
    routes:
      - id: FOURWHEELERSERVICE
        uri: lb://FOURWHEELERSERVICE
        predicates:
          - Path=/fourwheelers/**
      - id: HEAVYWHEELERSERVICE
        uri: lb://HEAVYWHEELERSERVICE
        predicates:
          - Path=/heavywheelers/**
      - id: THREEWHEELERSERVICE
        uri: lb://THREEWHEELERSERVICE
        predicates:
          - Path=/threewheelers/**
      - id: TWOWHEELERSERVICE
        uri: lb://TWOWHEELERSERVICE
        predicates:
          - Path=/twowheelers/**
