spring:
  application:
    name: SERVICEGATEWAY

  profiles:
    active: local

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: SELLERSERVICE
          uri: lb://SELLERSERVICE
          predicates:
            - Path=/sellers/**
          filters:
            - StripPrefix=1

        - id: BUYERSERVICE
          uri: lb://BUYERSERVICE
          predicates:
            - Path=/buyers/**
          filters:
            - StripPrefix=1

        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payments/**
          filters:
            - StripPrefix=1

server:
  port: 8181

logging:
  level:
    org.springframework.cloud.gateway: DEBUG